functionality:
  name: "take_column"
  namespace: "demo"
  version: "main_build"
  authors: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives:
    - "-i"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives:
    - "-o"
    example: []
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--column"
    alternatives: []
    example: []
    default:
    - 2
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--id"
    alternatives: []
    example: []
    default:
    - "take_column"
    required: false
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources: []
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.10-slim"
  target_organization: "viash-io/viash_project_template"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/viash-io/viash_project_template"
  setup:
  - type: "python"
    user: false
    packages:
    - "pandas"
    pip: []
    pypi: []
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/viash_project_template/viash_project_template/src/demo/take_column/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/viash_project_template/viash_project_template/target/nextflow/demo/take_column"
  executable: "/home/runner/work/viash_project_template/viash_project_template/target/nextflow/demo/take_column/take_column"
  viash_version: "0.7.1"
  git_commit: "ffa7b1bee3fb192bec568a772b44c6b527cd941b"
  git_remote: "https://github.com/viash-io/viash_project_template"
